export const empleados = [
	{
		nombre: "DULCE MARIA",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "CRUZ MARTINEZ",
		correo: "dulcemcmtz@hotmail.com",
		curp: "CUMD920411MGTRRL02",
		nombreUsuario: "dulcemcmtz",
		contrasenia: "Global2022",
		cantidadLicencias: "5",
		nombreEmpresa: "Walmart de Mexico",
	},
	{
		nombre: "LIZETH GUADALUPE",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "REYES PEDROZA",
		correo: "guadalupe161198@outlook.com",
		curp: "REPL981116MGTYDZ07",
		nombreUsuario: "guadalupe161198",
		contrasenia: "Global2022",
		cantidadLicencias: "10",
		nombreEmpresa: "Comisien Federal de Electricidad",
	},
	{
		nombre: "LIZBETH VIANNEY",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "PARRA LOPEZ",
		correo: "vianneylopez075@gmail.com",
		curp: "PALL981127MGTRPZ05",
		nombreUsuario: "vianneylopez075",
		contrasenia: "Global2022",
		cantidadLicencias: "20",
		nombreEmpresa: "FEMSA",
	},
	{
		nombre: "BLANCA GUADALUPE",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "VAZQUEZ ALFARO",
		correo: "blank230283@gmail.com",
		curp: "VAAB920223MGTZLL03",
		nombreUsuario: "blank230283",
		contrasenia: "Global2022",
		cantidadLicencias: "14",
		nombreEmpresa: "General Motors de Mexico",
	},
	{
		nombre: "CRUZ YESENIA DANIELA",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "ZENDEJAS LARA",
		correo: "c.y.d.zendejaslara@outlook.com",
		curp: "ZELC990423MGTNRR05",
		nombreUsuario: "c.y.d.zendejaslara",
		contrasenia: "Global2022",
		cantidadLicencias: "30",
		nombreEmpresa: "Alfa",
	},
	{
		nombre: "DULCE VERONICA",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "GARCIA RAMIREZ",
		correo: "dv.garcia0303@outlook.com",
		curp: "GARD721103MDFRML07",
		nombreUsuario: "dulcegarcia1402",
		contrasenia: "Global2022",
		cantidadLicencias: "100",
		nombreEmpresa: "FCA Mexico",
	},
	{
		nombre: "LAISHA FERNANDA",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "PADILLA AMEZQUITA",
		correo: "laishalion02@gmail.com",
		curp: "PAAL980806MJCDMS04",
		nombreUsuario: "laishalion02",
		contrasenia: "Global2022",
		cantidadLicencias: "51",
		nombreEmpresa: "Grupo Bimbo",
	},
	{
		nombre: "ELVA JAQUELINE",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "JUAREZ CASTILLO",
		correo: "elvajaquelinj@gmail.com",
		curp: "JUCE000411MGTRSLA9",
		nombreUsuario: "elvajaquelinj",
		contrasenia: "Global2022",
		cantidadLicencias: "32",
		nombreEmpresa: "Cemex",
	},
	{
		nombre: "VIRIDIANA DELGADO",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "GAONA",
		correo: "delgadoviridiana97@gmail.com",
		curp: "DEGV950815MGTLNR09",
		nombreUsuario: "delgadoviridiana97",
		contrasenia: "Global2022",
		cantidadLicencias: "16",
		nombreEmpresa: "Grupo Financiero BBVA Bancomer",
	},
	{
		nombre: "YURANI JANET GUADALUPE",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "RAMIREZ GALINDO",
		correo: "yuraniramirez189@gmail.com",
		curp: "RAGY001027MGTMLRA4",
		nombreUsuario: "yuraniramirez189",
		contrasenia: "Global2022",
		cantidadLicencias: "9",
		nombreEmpresa: "Volkswagen de Mexico",
	},
	{
		nombre: "SARAHI DEL ROCIO",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "PONCE LOPEZ",
		correo: "sarahiponce.24@gmail.com",
		curp: "POLS980602MGTNPR01",
		nombreUsuario: "sarahiponce.24",
		contrasenia: "Global2022",
		cantidadLicencias: "4",
		nombreEmpresa: "Nissan Mexicana",
	},
	{
		nombre: "JESSICA YADIRA",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "MAGANA GOMEZ",
		correo: "yaadi9827@gmail.com",
		curp: "MAGJ970712MGTGMS08",
		nombreUsuario: "yaadi9827@gmail.com",
		contrasenia: "Global2022",
		cantidadLicencias: "41",
		nombreEmpresa: "Grupo Financiero Banorte",
	},
	{
		nombre: "JAIR DE JESUS",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "RUIZ TOVAR",
		correo: "jairruiz046@gmail.com",
		curp: "RUTJ960509HMCZVR00",
		nombreUsuario: "jairruiz046",
		contrasenia: "Global2022",
		cantidadLicencias: "10",
		nombreEmpresa: "Honda de Mexico",
	},
	{
		nombre: "ERICK JAVIER",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "CAMARGO LIZJUAN",
		correo: "erickjavier1510@gmail.com",
		curp: "CALE981015HDFMZR06",
		nombreUsuario: "erickjavier1510",
		contrasenia: "Global2022",
		cantidadLicencias: "5",
		nombreEmpresa: "Ford de Mexico",
	},
	{
		nombre: "MIRZA ARGENIS",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "GONZALEZ ESPINOZA",
		correo: "mirgoespi@gmail.com",
		curp: "GOEM910926MSLNSR01",
		nombreUsuario: "mirgoespi@gmail.com",
		contrasenia: "Global2022",
		cantidadLicencias: "3",
		nombreEmpresa: "Grupo Coppel",
	},
	{
		nombre: "ARELY LIZETTE",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "HERNANDEZ HURTADO",
		correo: "gerarly_0322@hotmail.com",
		curp: "HEHA000122MGTRRRA1",
		nombreUsuario: "gerarly_0322",
		contrasenia: "Global2022",
		cantidadLicencias: "8",
		nombreEmpresa: "Arca Continental",
	},
	{
		nombre: "SUSANA LIZETTE",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "ONTIVEROS RAMIREZ",
		correo: "slor28@gmail.com",
		curp: "OIRS830228MGTNMS16",
		nombreUsuario: "slor28@gmail.com",
		contrasenia: "Global2022",
		cantidadLicencias: "4",
		nombreEmpresa: "Infonavit",
	},
	{
		nombre: "JORGE ALEXIS LEONARDO",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "CARDENAS POMPA",
		correo: "alex_20@hotmail.com",
		curp: "CAPJ961207HGTRMR02",
		nombreUsuario: "alex_20@hotmail.com",
		contrasenia: "Global2022",
		cantidadLicencias: "10",
		nombreEmpresa: "Grupo Financiero Santander Mexico",
	},
	{
		nombre: "JESSICA ELENA",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "HERNANDEZ PEREZ",
		correo: "reyesisma@hotmail.com",
		curp: "HEPJ860918MGTRRS07",
		nombreUsuario: "reyesisma",
		contrasenia: "Global2022",
		cantidadLicencias: "15",
		nombreEmpresa: "Grupo Salinas",
	},
	{
		nombre: "ALAN CHRISTOPHER",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "FLORES RAMIREZ",
		correo: "alanc_fr@hotmail.com",
		curp: "FORA001111HGTLMLA1",
		nombreUsuario: "alanc_fr@hotmail.com",
		contrasenia: "Global2022",
		cantidadLicencias: "45",
		nombreEmpresa: "Sam's Club",
	},
	{
		nombre: "EDUARDO ARIEL",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "CABRERA SALGADO",
		correo: "ecasal1297@icloud.com",
		curp: "CASE971212HDFBLD06",
		nombreUsuario: "ecasal1297",
		contrasenia: "Global2022",
		cantidadLicencias: "12",
		nombreEmpresa: "Ternium Mexico",
	},
	{
		nombre: "JUAN ALBERTO",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "VALADEZ MORENO",
		correo: "braveguy07@gmail.com",
		curp: "VAMJ980731HGTLRN07",
		nombreUsuario: "braveguy07@gmail.com",
		contrasenia: "Global2022",
		cantidadLicencias: "20",
		nombreEmpresa: "Sigma Alimentos",
	},
	{
		nombre: "MARTHA BEATRIZ",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "DIAZ MUNOZ",
		correo: "bmartha12@hotmail.com",
		curp: "DIMM990518MGTZXR00",
		nombreUsuario: "bmartha12",
		contrasenia: "Global2022",
		cantidadLicencias: "20",
		nombreEmpresa: "Grupo Comercial Chedraui",
	},
	{
		nombre: "DOLORES LILIANA",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "MORENO LOPEZ",
		correo: "liliana-morenolopez@hotmail.com",
		curp: "MOLD920410MGTRPL07",
		nombreUsuario: "liliana-morenolopez",
		contrasenia: "Global2022",
		cantidadLicencias: "12",
		nombreEmpresa: "Grupo Elektra",
	},
	{
		nombre: "REYNA CASANDRA",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "AGUIRRE AGUILERA",
		correo: "ingcivil.leon.reyna@gmail.com",
		curp: "AUAR950104MGTGGY08",
		nombreUsuario: "ingcivil.leon.reyna",
		contrasenia: "Global2022",
		cantidadLicencias: "4",
		nombreEmpresa: "Grupo Televisa",
	},
	{
		nombre: "RODRIGO JOSE",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "AGUERO ROBLEDO",
		correo: "rodrigo.08@outlook.com",
		curp: "AURR990529HGTGBD05",
		nombreUsuario: "rodrigo.08",
		contrasenia: "Global2022",
		cantidadLicencias: "8",
		nombreEmpresa: "Grupo Carso",
	},
	{
		nombre: "ARELY PAOLA",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "LEON SANCHEZ",
		correo: "paoleon0507@gmail.com",
		curp: "LESA970705MGTNNR02",
		nombreUsuario: "paoleon0507",
		contrasenia: "Global2022",
		cantidadLicencias: "5",
		nombreEmpresa: "Grupo Modelo",
	},
	{
		nombre: "DANIEL ALEJANDRO",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "RAMOS ZAVALA",
		correo: "danramos190@gmail.com",
		curp: "RAZD981220HGTMVN06",
		nombreUsuario: "danramos190",
		contrasenia: "Global2022",
		cantidadLicencias: "6",
		nombreEmpresa: "Grupo Proeza",
	},
	{
		nombre: "BRENDA MILAGROS",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "QUIROZ LOPEZ",
		correo: "brendaquiroz.47444@gmail.com",
		curp: "QULB990424MGTRPR07",
		nombreUsuario: "brendaquiroz.47444",
		contrasenia: "Global2022",
		cantidadLicencias: "8",
		nombreEmpresa: "Grupo Lala",
	},
	{
		nombre: "FERNANDA PATRICIA",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "RODRIGUEZ SANCHEZ",
		correo: "ferrodriguez2567@gmail.com",
		curp: "ROSF001125MGTDNRA5",
		nombreUsuario: "ferrodriguez2567",
		contrasenia: "Global2022",
		cantidadLicencias: "15",
		nombreEmpresa: "Cinepolis",
	},
	{
		nombre: "RICARDO AGUIRRE",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "PONCE",
		correo: "rap_cs@hotmail.com",
		curp: "AUPR850918HMNGNC03",
		nombreUsuario: "rap_cs@hotmail.com",
		contrasenia: "Global2022",
		cantidadLicencias: "20",
		nombreEmpresa: "Grupo Aeromexico",
	},
	{
		nombre: "SERGIO ANTONIO",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "HERNANDEZ RAMIREZ",
		correo: "sergioramirezcb24@gmail.com",
		curp: "HERS981111HGTRMR01",
		nombreUsuario: "sergiormz24",
		contrasenia: "Global2022",
		cantidadLicencias: "45",
		nombreEmpresa: "Continental Mexico",
	},
	{
		nombre: "EVELYN ESTEFANI",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "SANTANA MIRANDA",
		correo: "evsanmir@gmail.com",
		curp: "SAME920505MMCNRV09",
		nombreUsuario: "evsanmir@gmail.com",
		contrasenia: "Global2022",
		cantidadLicencias: "12",
		nombreEmpresa: "Industrias Bachoco",
	},
	{
		nombre: "LIZBET VALDES",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "TREJO",
		correo: "alitrejo19@gmail.com",
		curp: "VATL931119MDFLRZ16",
		nombreUsuario: "alitrejo19@gmail.com",
		contrasenia: "Global2022",
		cantidadLicencias: "10",
		nombreEmpresa: "Lear Corporation Mexico",
	},
	{
		nombre: "CECILIA BONILLA",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "ANDRADE",
		correo: "cbonilla30@gmail.com",
		curp: "BOAC890105MDFNNC02",
		nombreUsuario: "cbonilla30@gmail.com",
		contrasenia: "Global2022",
		cantidadLicencias: "8",
		nombreEmpresa: "AT&T Mexico",
	},
	{
		nombre: "MARIA DE LOURDES",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "CONTERAS HERNANDEZ",
		correo: "maria.contreras@hussmann.com",
		curp: "COHL750531MDFNRR07",
		nombreUsuario: "maria.contreras@hussmann.com",
		contrasenia: "Global2022",
		cantidadLicencias: "45",
		nombreEmpresa: "Grupo Villacero",
	},
	{
		nombre: "ULISES ORTEGA",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "JUAREZ",
		correo: "des.260592@gmail.com",
		curp: "OEJU920526HDFRRL00",
		nombreUsuario: "des.260592@gmail.com",
		contrasenia: "Global2022",
		cantidadLicencias: "22",
		nombreEmpresa: "SuKarne",
	},
	{
		nombre: "Mayra Guadalupe",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "Jaimez Tapia",
		correo: "jaimeztapiamayraguadalupe@gmail.com",
		curp: "JATM00004MGTMPYA4",
		nombreUsuario: "jaimeztapiamayraguadalupe",
		contrasenia: "Global2022",
		cantidadLicencias: "29",
		nombreEmpresa: "Grupo Sanborns",
	},
	{
		nombre: "Nayeli de la Cruz",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "MORALES",
		correo: "cruzmoralesrangel@gmail.com",
		curp: "MORN990120MGTRNY07",
		nombreUsuario: "cruzmoralesrangel@gmail.com",
		contrasenia: "Global2022",
		cantidadLicencias: "30",
		nombreEmpresa: "LG Electronics Mexico",
	},
	{
		nombre: "Brenda Cecilia",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "Hernendez Lepez",
		correo: "burtoncecilia522@gmail.com",
		curp: "HELB001120MGTRPRA6",
		nombreUsuario: "burtoncecilia522@gmail.com",
		contrasenia: "Global2022",
		cantidadLicencias: "40",
		nombreEmpresa: "American Axle Manufacturing de Mexico",
	},
	{
		nombre: "Jacqueline Adriana",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "Gemez Millen",
		correo: "jacqueline7749@gmail.com",
		curp: "GOMJ960303MGTMLC08",
		nombreUsuario: "jacqueline7749@gmail.com",
		contrasenia: "Global2022",
		cantidadLicencias: "10",
		nombreEmpresa: "KIA Motors Mexico",
	},
	{
		nombre: "Miriam Araceli",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "Perez Ramerez",
		correo: "miriamquitana.lovv24@gmail.com",
		curp: "PERM931029MGTRMR08",
		nombreUsuario: "miriamquitana.lovv24@gmail.com",
		contrasenia: "Global2022",
		cantidadLicencias: "5",
		nombreEmpresa: "The Home Depot Mexico",
	},
	{
		nombre: "Gloria del Carmen",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "Moreno Esquivel",
		correo: "glo.rymoreno32@gmail.com",
		curp: "MOEG000318MGTRSLA3",
		nombreUsuario: "glo.rymoreno32@gmail.com",
		contrasenia: "Global2022",
		cantidadLicencias: "4",
		nombreEmpresa: "P&G Mexico",
	},
	{
		nombre: "Lissette Daniela",
		idMembresia: "5",
		folioContrato: "750",
		apellidos: "Cruz Ramerez",
		correo: "lissdani0905@gmail.com",
		curp: "CURL960509MGTRMS01",
		nombreUsuario: "lissdani0905@gmail.com",
		contrasenia: "Global2022",
		cantidadLicencias: "9",
		nombreEmpresa: "Grupo Mexico Divisien Transportes",
	},
];
